name: Passo 3

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/**"

permissions:
  contents: read
  actions: write
  issues: write

env:
  STEP_4_FILE: ".github/steps/4-play-time.md"

jobs:
  find_exercise:
    name: Encontrar Issue do exercício
    uses: dev-pods/exercise-toolkit/.github/workflows/find-exercise-issue.yml@v0.1.1

  check_step_work:
    name: Verificar trabalho do passo
    runs-on: ubuntu-latest
    needs: [find_exercise]
    env:
      ISSUE_URL: ${{ needs.find_exercise.outputs.issue-url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Obter templates de resposta
        uses: actions/checkout@v4
        with:
          repository: dev-pods/exercise-toolkit
          path: exercise-toolkit
          ref: v0.1.1

      - name: Atualizar comentário - verificando trabalho
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file exercise-toolkit/markdown-templates/step-feedback/checking-work.md \
            --edit-last
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # INÍCIO: Verificar exercício prático

      - name: Verificar mudanças nos arquivos
        id: changed-files
        uses: tj-actions/changed-files@v46.0.5

      - name: Verificar copilot-instructions.md
        id: check-instructions
        uses: actions/github-script@v6
        continue-on-error: true
        with:
          script: |
            const changedFiles = '${{ steps.changed-files.outputs.all_changed_files }}'.split(' ');
            let message = '';

            if (!changedFiles.includes('.github/copilot-instructions.md')) {
              message = 'Você precisa fornecer instruções no arquivo .github/copilot-instructions.md';
              core.setOutput('STEP_MESSAGE', message);
              core.setFailed('O arquivo .github/copilot-instructions.md não foi modificado');
              return;
            }

            message = 'Instruções fornecidas em `.github/copilot-instructions.md`';
            core.setOutput('STEP_MESSAGE', message);

      - name: Verificar copilot-setup-steps.yml
        id: check-setup-steps
        uses: actions/github-script@v6
        continue-on-error: true
        with:
          script: |
            const changedFiles = '${{ steps.changed-files.outputs.all_changed_files }}'.split(' ');
            let message = '';

            if (!changedFiles.includes('.github/workflows/copilot-setup-steps.yml')) {
              message = 'Você precisa configurar o workflow copilot-setup-steps.yml';
              core.setOutput('STEP_MESSAGE', message);
              core.setFailed('O arquivo `copilot-setup-steps.yml` não foi modificado');
              return;
            }

            message = 'Você configurou o workflow copilot-setup-steps.yml';
            core.setOutput('STEP_MESSAGE', message);

      - name: Construir mensagem - resultados do passo
        id: build-message-step-results
        uses: dev-pods/action-text-variables@v0.0.1
        with:
          template-file: exercise-toolkit/markdown-templates/step-feedback/step-results-table.md
          template-vars: |
            step_number: 3
            passed: ${{ !contains(steps.*.outcome, 'failure') }}
            results_table:
              - description: ${{ steps.check-instructions.outputs.STEP_MESSAGE }}
                passed: ${{ steps.check-instructions.outcome == 'success' }}
              - description: ${{ steps.check-setup-steps.outputs.STEP_MESSAGE }}
                passed: ${{ steps.check-setup-steps.outcome == 'success' }}

      - name: Criar comentário - resultados do passo
        run: |
          gh issue comment "$ISSUE_URL" \
            --body "$COMMENT_BODY" \
            --edit-last
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_BODY: ${{ steps.build-message-step-results.outputs.updated-text }}

      # FIM: Verificar exercício prático

      - name: Falhar job se nem todas as verificações passaram
        if: contains(steps.*.outcome, 'failure')
        run: exit 1

      - name: Construir mensagem - passo finalizado
        id: build-message-step-finish
        uses: dev-pods/action-text-variables@v0.0.1
        with:
          template-file: exercise-toolkit/markdown-templates/step-feedback/step-finished-prepare-next-step.md
          template-vars: |
            next_step_number: 4

      - name: Adicionar comentário - passo finalizado
        run: |
          gh issue comment "$ISSUE_URL" \
            --body "$ISSUE_BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_BODY: ${{ steps.build-message-step-finish.outputs.updated-text }}

  post_next_step_content:
    name: Postar conteúdo do próximo passo
    needs: [find_exercise, check_step_work]
    runs-on: ubuntu-latest
    env:
      ISSUE_URL: ${{ needs.find_exercise.outputs.issue-url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Obter templates de resposta
        uses: actions/checkout@v4
        with:
          repository: dev-pods/exercise-toolkit
          path: exercise-toolkit
          ref: v0.1.1

      - name: Criar comentário - adicionar conteúdo do passo
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file "$STEP_4_FILE"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Criar comentário - observando progresso
        run: |
          gh issue comment "$ISSUE_URL" \
            --body-file exercise-toolkit/markdown-templates/step-feedback/watching-for-progress.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Desabilitar workflow atual e habilitar o próximo
        run: |
          gh workflow disable "Step 3" || true
          gh workflow enable "Step 4" || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
